-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pointwise_conv2d_fix_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of pointwise_conv2d_fix_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv9_31 : STD_LOGIC_VECTOR (8 downto 0) := "000110001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv9_188 : STD_LOGIC_VECTOR (8 downto 0) := "110001000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv7_38 : STD_LOGIC_VECTOR (6 downto 0) := "0111000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv16_2A92 : STD_LOGIC_VECTOR (15 downto 0) := "0010101010010010";
    constant ap_const_lv16_18D9 : STD_LOGIC_VECTOR (15 downto 0) := "0001100011011001";
    constant ap_const_lv16_F240 : STD_LOGIC_VECTOR (15 downto 0) := "1111001001000000";
    constant ap_const_lv16_DF5 : STD_LOGIC_VECTOR (15 downto 0) := "0000110111110101";
    constant ap_const_lv16_E1AB : STD_LOGIC_VECTOR (15 downto 0) := "1110000110101011";
    constant ap_const_lv16_FF67 : STD_LOGIC_VECTOR (15 downto 0) := "1111111101100111";
    constant ap_const_lv16_273B : STD_LOGIC_VECTOR (15 downto 0) := "0010011100111011";
    constant ap_const_lv16_1B40 : STD_LOGIC_VECTOR (15 downto 0) := "0001101101000000";
    constant ap_const_lv16_23D : STD_LOGIC_VECTOR (15 downto 0) := "0000001000111101";
    constant ap_const_lv16_E3EC : STD_LOGIC_VECTOR (15 downto 0) := "1110001111101100";
    constant ap_const_lv16_18CC : STD_LOGIC_VECTOR (15 downto 0) := "0001100011001100";
    constant ap_const_lv16_DB60 : STD_LOGIC_VECTOR (15 downto 0) := "1101101101100000";
    constant ap_const_lv16_DC1A : STD_LOGIC_VECTOR (15 downto 0) := "1101110000011010";
    constant ap_const_lv16_EADB : STD_LOGIC_VECTOR (15 downto 0) := "1110101011011011";
    constant ap_const_lv16_FC94 : STD_LOGIC_VECTOR (15 downto 0) := "1111110010010100";
    constant ap_const_lv16_FFD8 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111011000";
    constant ap_const_lv16_DF7C : STD_LOGIC_VECTOR (15 downto 0) := "1101111101111100";
    constant ap_const_lv16_831 : STD_LOGIC_VECTOR (15 downto 0) := "0000100000110001";
    constant ap_const_lv16_DAF1 : STD_LOGIC_VECTOR (15 downto 0) := "1101101011110001";
    constant ap_const_lv16_E615 : STD_LOGIC_VECTOR (15 downto 0) := "1110011000010101";
    constant ap_const_lv16_25F : STD_LOGIC_VECTOR (15 downto 0) := "0000001001011111";
    constant ap_const_lv16_E06F : STD_LOGIC_VECTOR (15 downto 0) := "1110000001101111";
    constant ap_const_lv16_1EBB : STD_LOGIC_VECTOR (15 downto 0) := "0001111010111011";
    constant ap_const_lv16_EAA6 : STD_LOGIC_VECTOR (15 downto 0) := "1110101010100110";
    constant ap_const_lv16_2D1B : STD_LOGIC_VECTOR (15 downto 0) := "0010110100011011";
    constant ap_const_lv16_20DD : STD_LOGIC_VECTOR (15 downto 0) := "0010000011011101";
    constant ap_const_lv16_F939 : STD_LOGIC_VECTOR (15 downto 0) := "1111100100111001";
    constant ap_const_lv16_2125 : STD_LOGIC_VECTOR (15 downto 0) := "0010000100100101";
    constant ap_const_lv16_A69 : STD_LOGIC_VECTOR (15 downto 0) := "0000101001101001";
    constant ap_const_lv16_D5F : STD_LOGIC_VECTOR (15 downto 0) := "0000110101011111";
    constant ap_const_lv16_FC6E : STD_LOGIC_VECTOR (15 downto 0) := "1111110001101110";
    constant ap_const_lv16_11D0 : STD_LOGIC_VECTOR (15 downto 0) := "0001000111010000";
    constant ap_const_lv16_E860 : STD_LOGIC_VECTOR (15 downto 0) := "1110100001100000";
    constant ap_const_lv16_1B74 : STD_LOGIC_VECTOR (15 downto 0) := "0001101101110100";
    constant ap_const_lv16_E946 : STD_LOGIC_VECTOR (15 downto 0) := "1110100101000110";
    constant ap_const_lv16_24BD : STD_LOGIC_VECTOR (15 downto 0) := "0010010010111101";
    constant ap_const_lv16_19BA : STD_LOGIC_VECTOR (15 downto 0) := "0001100110111010";
    constant ap_const_lv16_1350 : STD_LOGIC_VECTOR (15 downto 0) := "0001001101010000";
    constant ap_const_lv16_1D74 : STD_LOGIC_VECTOR (15 downto 0) := "0001110101110100";
    constant ap_const_lv16_21B5 : STD_LOGIC_VECTOR (15 downto 0) := "0010000110110101";
    constant ap_const_lv16_19A4 : STD_LOGIC_VECTOR (15 downto 0) := "0001100110100100";
    constant ap_const_lv16_D684 : STD_LOGIC_VECTOR (15 downto 0) := "1101011010000100";
    constant ap_const_lv16_F909 : STD_LOGIC_VECTOR (15 downto 0) := "1111100100001001";
    constant ap_const_lv16_170B : STD_LOGIC_VECTOR (15 downto 0) := "0001011100001011";
    constant ap_const_lv16_DFAC : STD_LOGIC_VECTOR (15 downto 0) := "1101111110101100";
    constant ap_const_lv16_2F75 : STD_LOGIC_VECTOR (15 downto 0) := "0010111101110101";
    constant ap_const_lv16_B43 : STD_LOGIC_VECTOR (15 downto 0) := "0000101101000011";
    constant ap_const_lv16_ED88 : STD_LOGIC_VECTOR (15 downto 0) := "1110110110001000";
    constant ap_const_lv16_259C : STD_LOGIC_VECTOR (15 downto 0) := "0010010110011100";
    constant ap_const_lv16_1F9D : STD_LOGIC_VECTOR (15 downto 0) := "0001111110011101";
    constant ap_const_lv16_2DD : STD_LOGIC_VECTOR (15 downto 0) := "0000001011011101";
    constant ap_const_lv16_2357 : STD_LOGIC_VECTOR (15 downto 0) := "0010001101010111";
    constant ap_const_lv16_EF4E : STD_LOGIC_VECTOR (15 downto 0) := "1110111101001110";
    constant ap_const_lv16_FB37 : STD_LOGIC_VECTOR (15 downto 0) := "1111101100110111";
    constant ap_const_lv16_E619 : STD_LOGIC_VECTOR (15 downto 0) := "1110011000011001";
    constant ap_const_lv16_F172 : STD_LOGIC_VECTOR (15 downto 0) := "1111000101110010";
    constant ap_const_lv16_6B8 : STD_LOGIC_VECTOR (15 downto 0) := "0000011010111000";
    constant ap_const_lv16_867 : STD_LOGIC_VECTOR (15 downto 0) := "0000100001100111";
    constant ap_const_lv16_F876 : STD_LOGIC_VECTOR (15 downto 0) := "1111100001110110";
    constant ap_const_lv16_13D9 : STD_LOGIC_VECTOR (15 downto 0) := "0001001111011001";
    constant ap_const_lv16_FE67 : STD_LOGIC_VECTOR (15 downto 0) := "1111111001100111";
    constant ap_const_lv16_E8FC : STD_LOGIC_VECTOR (15 downto 0) := "1110100011111100";
    constant ap_const_lv16_F03B : STD_LOGIC_VECTOR (15 downto 0) := "1111000000111011";
    constant ap_const_lv16_7A4 : STD_LOGIC_VECTOR (15 downto 0) := "0000011110100100";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv10_31 : STD_LOGIC_VECTOR (9 downto 0) := "0000110001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal SeparableConv2D_2_b_s_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal SeparableConv2D_2_b_s_ce0 : STD_LOGIC;
    signal SeparableConv2D_2_b_s_q0 : STD_LOGIC_VECTOR (12 downto 0);
    signal indvar_flatten20_reg_266 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_h_0_reg_278 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten_reg_290 : STD_LOGIC_VECTOR (6 downto 0);
    signal in_d_0_reg_301 : STD_LOGIC_VECTOR (3 downto 0);
    signal out_w_0_reg_313 : STD_LOGIC_VECTOR (2 downto 0);
    signal buffer_0_reg_324 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln19_fu_334_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln19_reg_807 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal out_d_fu_346_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal out_d_reg_815 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln19_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_fu_357_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln29_reg_825 : STD_LOGIC_VECTOR (2 downto 0);
    signal SeparableConv2D_2_b_3_reg_830 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal sext_ln29_fu_361_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln29_reg_835 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal shl_ln_fu_364_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln_reg_842 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln29_fu_387_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln29_reg_847 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state5_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln20_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_reg_853 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_reg_853_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_reg_853_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_reg_853_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_reg_853_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_h_fu_399_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal out_h_reg_857 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln21_fu_405_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_reg_864 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_reg_864_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_reg_864_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_reg_864_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_fu_411_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_876 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln21_fu_417_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln21_reg_881 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_fu_427_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_reg_886 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state6_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state9_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state12_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_state15_pp0_stage1_iter3 : BOOLEAN;
    signal ap_block_state18_pp0_stage1_iter4 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal add_ln20_fu_432_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln20_reg_891 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal select_ln29_fu_438_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln29_reg_896 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln29_3_fu_459_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln29_3_reg_902 : STD_LOGIC_VECTOR (6 downto 0);
    signal and_ln29_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln29_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln29_reg_908_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln29_reg_908_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln20_fu_475_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln20_reg_916 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln29_7_fu_481_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln29_7_reg_921 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_state7_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_state10_pp0_stage2_iter1 : BOOLEAN;
    signal ap_block_state13_pp0_stage2_iter2 : BOOLEAN;
    signal ap_block_state16_pp0_stage2_iter3 : BOOLEAN;
    signal ap_block_state19_pp0_stage2_iter4 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal out_w_fu_486_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal out_w_reg_927 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln24_6_fu_495_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln24_6_reg_933 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln21_fu_503_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln21_reg_940 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln24_7_fu_509_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln24_7_reg_945 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal add_ln29_7_fu_517_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_7_reg_951 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_6_fu_525_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln29_6_reg_956 : STD_LOGIC_VECTOR (5 downto 0);
    signal in_d_fu_530_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal in_d_reg_961 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln24_8_fu_543_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln24_8_reg_967 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln24_3_fu_682_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_3_reg_972 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_3_reg_972_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_3_reg_972_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_3_reg_972_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln34_fu_687_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln34_reg_976 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_793_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln29_1_reg_981 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln34_1_fu_705_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln34_1_reg_986 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln34_1_reg_986_pp0_iter2_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln34_1_reg_986_pp0_iter3_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal input_load_reg_996 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_549_p66 : STD_LOGIC_VECTOR (15 downto 0);
    signal merge_i_reg_1001 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln24_fu_725_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln24_reg_1006 : STD_LOGIC_VECTOR (21 downto 0);
    signal mul_ln29_2_fu_801_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln29_2_reg_1011 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_750_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal buffer_reg_1021 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal and_ln34_fu_779_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln34_reg_1028 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state6 : STD_LOGIC;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal out_d_0_reg_243 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal phi_mul_reg_254 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_mux_indvar_flatten20_phi_fu_270_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_mux_out_h_0_phi_fu_282_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_indvar_flatten_phi_fu_294_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_phi_mux_in_d_0_phi_fu_305_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_mux_out_w_0_phi_fu_317_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_phi_mux_buffer_0_phi_fu_327_p4 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln23_fu_352_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln29_7_fu_714_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln34_fu_788_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal shl_ln29_4_fu_375_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln29_12_fu_383_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln29_fu_371_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln24_3_fu_423_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln29_4_mid1_fu_448_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln29_14_fu_455_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln29_13_fu_445_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal xor_ln29_fu_465_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln24_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln24_4_fu_514_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln29_16_fu_522_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln29_8_fu_535_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln24_fu_540_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln34_3_fu_702_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln29_7_fu_693_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln29_8_fu_711_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln29_6_fu_719_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal trunc_ln_fu_737_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_750_p0 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_3_fu_755_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln33_fu_765_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln33_fu_771_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln33_fu_762_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln34_fu_785_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_793_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_793_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_793_p00 : STD_LOGIC_VECTOR (9 downto 0);

    component network_mux_646_16_6_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        din17_WIDTH : INTEGER;
        din18_WIDTH : INTEGER;
        din19_WIDTH : INTEGER;
        din20_WIDTH : INTEGER;
        din21_WIDTH : INTEGER;
        din22_WIDTH : INTEGER;
        din23_WIDTH : INTEGER;
        din24_WIDTH : INTEGER;
        din25_WIDTH : INTEGER;
        din26_WIDTH : INTEGER;
        din27_WIDTH : INTEGER;
        din28_WIDTH : INTEGER;
        din29_WIDTH : INTEGER;
        din30_WIDTH : INTEGER;
        din31_WIDTH : INTEGER;
        din32_WIDTH : INTEGER;
        din33_WIDTH : INTEGER;
        din34_WIDTH : INTEGER;
        din35_WIDTH : INTEGER;
        din36_WIDTH : INTEGER;
        din37_WIDTH : INTEGER;
        din38_WIDTH : INTEGER;
        din39_WIDTH : INTEGER;
        din40_WIDTH : INTEGER;
        din41_WIDTH : INTEGER;
        din42_WIDTH : INTEGER;
        din43_WIDTH : INTEGER;
        din44_WIDTH : INTEGER;
        din45_WIDTH : INTEGER;
        din46_WIDTH : INTEGER;
        din47_WIDTH : INTEGER;
        din48_WIDTH : INTEGER;
        din49_WIDTH : INTEGER;
        din50_WIDTH : INTEGER;
        din51_WIDTH : INTEGER;
        din52_WIDTH : INTEGER;
        din53_WIDTH : INTEGER;
        din54_WIDTH : INTEGER;
        din55_WIDTH : INTEGER;
        din56_WIDTH : INTEGER;
        din57_WIDTH : INTEGER;
        din58_WIDTH : INTEGER;
        din59_WIDTH : INTEGER;
        din60_WIDTH : INTEGER;
        din61_WIDTH : INTEGER;
        din62_WIDTH : INTEGER;
        din63_WIDTH : INTEGER;
        din64_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        din4 : IN STD_LOGIC_VECTOR (15 downto 0);
        din5 : IN STD_LOGIC_VECTOR (15 downto 0);
        din6 : IN STD_LOGIC_VECTOR (15 downto 0);
        din7 : IN STD_LOGIC_VECTOR (15 downto 0);
        din8 : IN STD_LOGIC_VECTOR (15 downto 0);
        din9 : IN STD_LOGIC_VECTOR (15 downto 0);
        din10 : IN STD_LOGIC_VECTOR (15 downto 0);
        din11 : IN STD_LOGIC_VECTOR (15 downto 0);
        din12 : IN STD_LOGIC_VECTOR (15 downto 0);
        din13 : IN STD_LOGIC_VECTOR (15 downto 0);
        din14 : IN STD_LOGIC_VECTOR (15 downto 0);
        din15 : IN STD_LOGIC_VECTOR (15 downto 0);
        din16 : IN STD_LOGIC_VECTOR (15 downto 0);
        din17 : IN STD_LOGIC_VECTOR (15 downto 0);
        din18 : IN STD_LOGIC_VECTOR (15 downto 0);
        din19 : IN STD_LOGIC_VECTOR (15 downto 0);
        din20 : IN STD_LOGIC_VECTOR (15 downto 0);
        din21 : IN STD_LOGIC_VECTOR (15 downto 0);
        din22 : IN STD_LOGIC_VECTOR (15 downto 0);
        din23 : IN STD_LOGIC_VECTOR (15 downto 0);
        din24 : IN STD_LOGIC_VECTOR (15 downto 0);
        din25 : IN STD_LOGIC_VECTOR (15 downto 0);
        din26 : IN STD_LOGIC_VECTOR (15 downto 0);
        din27 : IN STD_LOGIC_VECTOR (15 downto 0);
        din28 : IN STD_LOGIC_VECTOR (15 downto 0);
        din29 : IN STD_LOGIC_VECTOR (15 downto 0);
        din30 : IN STD_LOGIC_VECTOR (15 downto 0);
        din31 : IN STD_LOGIC_VECTOR (15 downto 0);
        din32 : IN STD_LOGIC_VECTOR (15 downto 0);
        din33 : IN STD_LOGIC_VECTOR (15 downto 0);
        din34 : IN STD_LOGIC_VECTOR (15 downto 0);
        din35 : IN STD_LOGIC_VECTOR (15 downto 0);
        din36 : IN STD_LOGIC_VECTOR (15 downto 0);
        din37 : IN STD_LOGIC_VECTOR (15 downto 0);
        din38 : IN STD_LOGIC_VECTOR (15 downto 0);
        din39 : IN STD_LOGIC_VECTOR (15 downto 0);
        din40 : IN STD_LOGIC_VECTOR (15 downto 0);
        din41 : IN STD_LOGIC_VECTOR (15 downto 0);
        din42 : IN STD_LOGIC_VECTOR (15 downto 0);
        din43 : IN STD_LOGIC_VECTOR (15 downto 0);
        din44 : IN STD_LOGIC_VECTOR (15 downto 0);
        din45 : IN STD_LOGIC_VECTOR (15 downto 0);
        din46 : IN STD_LOGIC_VECTOR (15 downto 0);
        din47 : IN STD_LOGIC_VECTOR (15 downto 0);
        din48 : IN STD_LOGIC_VECTOR (15 downto 0);
        din49 : IN STD_LOGIC_VECTOR (15 downto 0);
        din50 : IN STD_LOGIC_VECTOR (15 downto 0);
        din51 : IN STD_LOGIC_VECTOR (15 downto 0);
        din52 : IN STD_LOGIC_VECTOR (15 downto 0);
        din53 : IN STD_LOGIC_VECTOR (15 downto 0);
        din54 : IN STD_LOGIC_VECTOR (15 downto 0);
        din55 : IN STD_LOGIC_VECTOR (15 downto 0);
        din56 : IN STD_LOGIC_VECTOR (15 downto 0);
        din57 : IN STD_LOGIC_VECTOR (15 downto 0);
        din58 : IN STD_LOGIC_VECTOR (15 downto 0);
        din59 : IN STD_LOGIC_VECTOR (15 downto 0);
        din60 : IN STD_LOGIC_VECTOR (15 downto 0);
        din61 : IN STD_LOGIC_VECTOR (15 downto 0);
        din62 : IN STD_LOGIC_VECTOR (15 downto 0);
        din63 : IN STD_LOGIC_VECTOR (15 downto 0);
        din64 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component network_add_22s_22ns_22_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (21 downto 0);
        din1 : IN STD_LOGIC_VECTOR (21 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (21 downto 0) );
    end component;


    component network_mac_muladd_4ns_7ns_7s_10_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component network_mul_mul_16s_16s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component pointwise_conv2d_fix_2_SeparableConv2D_2_b_s IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;



begin
    SeparableConv2D_2_b_s_U : component pointwise_conv2d_fix_2_SeparableConv2D_2_b_s
    generic map (
        DataWidth => 13,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => SeparableConv2D_2_b_s_address0,
        ce0 => SeparableConv2D_2_b_s_ce0,
        q0 => SeparableConv2D_2_b_s_q0);

    network_mux_646_16_6_1_U102 : component network_mux_646_16_6_1
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 16,
        din5_WIDTH => 16,
        din6_WIDTH => 16,
        din7_WIDTH => 16,
        din8_WIDTH => 16,
        din9_WIDTH => 16,
        din10_WIDTH => 16,
        din11_WIDTH => 16,
        din12_WIDTH => 16,
        din13_WIDTH => 16,
        din14_WIDTH => 16,
        din15_WIDTH => 16,
        din16_WIDTH => 16,
        din17_WIDTH => 16,
        din18_WIDTH => 16,
        din19_WIDTH => 16,
        din20_WIDTH => 16,
        din21_WIDTH => 16,
        din22_WIDTH => 16,
        din23_WIDTH => 16,
        din24_WIDTH => 16,
        din25_WIDTH => 16,
        din26_WIDTH => 16,
        din27_WIDTH => 16,
        din28_WIDTH => 16,
        din29_WIDTH => 16,
        din30_WIDTH => 16,
        din31_WIDTH => 16,
        din32_WIDTH => 16,
        din33_WIDTH => 16,
        din34_WIDTH => 16,
        din35_WIDTH => 16,
        din36_WIDTH => 16,
        din37_WIDTH => 16,
        din38_WIDTH => 16,
        din39_WIDTH => 16,
        din40_WIDTH => 16,
        din41_WIDTH => 16,
        din42_WIDTH => 16,
        din43_WIDTH => 16,
        din44_WIDTH => 16,
        din45_WIDTH => 16,
        din46_WIDTH => 16,
        din47_WIDTH => 16,
        din48_WIDTH => 16,
        din49_WIDTH => 16,
        din50_WIDTH => 16,
        din51_WIDTH => 16,
        din52_WIDTH => 16,
        din53_WIDTH => 16,
        din54_WIDTH => 16,
        din55_WIDTH => 16,
        din56_WIDTH => 16,
        din57_WIDTH => 16,
        din58_WIDTH => 16,
        din59_WIDTH => 16,
        din60_WIDTH => 16,
        din61_WIDTH => 16,
        din62_WIDTH => 16,
        din63_WIDTH => 16,
        din64_WIDTH => 6,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_const_lv16_2A92,
        din1 => ap_const_lv16_18D9,
        din2 => ap_const_lv16_F240,
        din3 => ap_const_lv16_DF5,
        din4 => ap_const_lv16_E1AB,
        din5 => ap_const_lv16_FF67,
        din6 => ap_const_lv16_273B,
        din7 => ap_const_lv16_1B40,
        din8 => ap_const_lv16_23D,
        din9 => ap_const_lv16_E3EC,
        din10 => ap_const_lv16_18CC,
        din11 => ap_const_lv16_DB60,
        din12 => ap_const_lv16_DC1A,
        din13 => ap_const_lv16_EADB,
        din14 => ap_const_lv16_FC94,
        din15 => ap_const_lv16_FFD8,
        din16 => ap_const_lv16_DF7C,
        din17 => ap_const_lv16_831,
        din18 => ap_const_lv16_DAF1,
        din19 => ap_const_lv16_E615,
        din20 => ap_const_lv16_25F,
        din21 => ap_const_lv16_E06F,
        din22 => ap_const_lv16_1EBB,
        din23 => ap_const_lv16_EAA6,
        din24 => ap_const_lv16_2D1B,
        din25 => ap_const_lv16_20DD,
        din26 => ap_const_lv16_F939,
        din27 => ap_const_lv16_2125,
        din28 => ap_const_lv16_A69,
        din29 => ap_const_lv16_D5F,
        din30 => ap_const_lv16_FC6E,
        din31 => ap_const_lv16_11D0,
        din32 => ap_const_lv16_E860,
        din33 => ap_const_lv16_1B74,
        din34 => ap_const_lv16_E946,
        din35 => ap_const_lv16_24BD,
        din36 => ap_const_lv16_19BA,
        din37 => ap_const_lv16_1350,
        din38 => ap_const_lv16_1D74,
        din39 => ap_const_lv16_21B5,
        din40 => ap_const_lv16_19A4,
        din41 => ap_const_lv16_D684,
        din42 => ap_const_lv16_F909,
        din43 => ap_const_lv16_170B,
        din44 => ap_const_lv16_DFAC,
        din45 => ap_const_lv16_2F75,
        din46 => ap_const_lv16_B43,
        din47 => ap_const_lv16_ED88,
        din48 => ap_const_lv16_259C,
        din49 => ap_const_lv16_1F9D,
        din50 => ap_const_lv16_2DD,
        din51 => ap_const_lv16_2357,
        din52 => ap_const_lv16_EF4E,
        din53 => ap_const_lv16_FB37,
        din54 => ap_const_lv16_E619,
        din55 => ap_const_lv16_F172,
        din56 => ap_const_lv16_6B8,
        din57 => ap_const_lv16_867,
        din58 => ap_const_lv16_F876,
        din59 => ap_const_lv16_13D9,
        din60 => ap_const_lv16_FE67,
        din61 => ap_const_lv16_E8FC,
        din62 => ap_const_lv16_F03B,
        din63 => ap_const_lv16_7A4,
        din64 => add_ln29_6_reg_956,
        ce => ap_const_logic_1,
        dout => grp_fu_549_p66);

    network_add_22s_22ns_22_2_1_U103 : component network_add_22s_22ns_22_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 22,
        din1_WIDTH => 22,
        dout_WIDTH => 22)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_750_p0,
        din1 => select_ln24_reg_1006,
        ce => ap_const_logic_1,
        dout => grp_fu_750_p2);

    network_mac_muladd_4ns_7ns_7s_10_1_1_U104 : component network_mac_muladd_4ns_7ns_7s_10_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 7,
        din2_WIDTH => 7,
        dout_WIDTH => 10)
    port map (
        din0 => grp_fu_793_p0,
        din1 => grp_fu_793_p1,
        din2 => select_ln24_8_reg_967,
        dout => grp_fu_793_p3);

    network_mul_mul_16s_16s_32_1_1_U105 : component network_mul_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => merge_i_reg_1001,
        din1 => input_load_reg_996,
        dout => mul_ln29_2_fu_801_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    buffer_0_reg_324_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853_pp0_iter4_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                buffer_0_reg_324 <= buffer_reg_1021;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                buffer_0_reg_324 <= sext_ln29_fu_361_p1;
            end if; 
        end if;
    end process;

    in_d_0_reg_301_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                in_d_0_reg_301 <= in_d_fu_530_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                in_d_0_reg_301 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    indvar_flatten20_reg_266_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten20_reg_266 <= add_ln20_reg_891;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                indvar_flatten20_reg_266 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_290_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten_reg_290 <= select_ln21_reg_940;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                indvar_flatten_reg_290 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    out_d_0_reg_243_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
                out_d_0_reg_243 <= out_d_reg_815;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_d_0_reg_243 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    out_h_0_reg_278_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                out_h_0_reg_278 <= select_ln20_reg_916;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                out_h_0_reg_278 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    out_w_0_reg_313_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                out_w_0_reg_313 <= select_ln24_7_reg_945;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                out_w_0_reg_313 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    phi_mul_reg_254_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
                phi_mul_reg_254 <= add_ln19_reg_807;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                phi_mul_reg_254 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                SeparableConv2D_2_b_3_reg_830 <= SeparableConv2D_2_b_s_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln19_reg_807 <= add_ln19_fu_334_p2;
                out_d_reg_815 <= out_d_fu_346_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                add_ln20_reg_891 <= add_ln20_fu_432_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_fu_393_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln21_reg_881 <= add_ln21_fu_417_p2;
                icmp_ln21_reg_864 <= icmp_ln21_fu_405_p2;
                icmp_ln24_reg_876 <= icmp_ln24_fu_411_p2;
                out_h_reg_857 <= out_h_fu_399_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then
                add_ln29_1_reg_981 <= grp_fu_793_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln29_6_reg_956 <= add_ln29_6_fu_525_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_lv1_1 = and_ln29_reg_908) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln29_7_reg_951 <= add_ln29_7_fu_517_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln21_reg_864 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                add_ln29_reg_886 <= add_ln29_fu_427_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln24_3_reg_972 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then
                add_ln34_1_reg_986 <= add_ln34_1_fu_705_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then
                add_ln34_1_reg_986_pp0_iter2_reg <= add_ln34_1_reg_986;
                add_ln34_1_reg_986_pp0_iter3_reg <= add_ln34_1_reg_986_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln24_3_fu_682_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                add_ln34_reg_976 <= add_ln34_fu_687_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                and_ln29_reg_908 <= and_ln29_fu_470_p2;
                select_ln29_reg_896 <= select_ln29_fu_438_p3;
                sub_ln29_3_reg_902 <= sub_ln29_3_fu_459_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                and_ln29_reg_908_pp0_iter1_reg <= and_ln29_reg_908;
                and_ln29_reg_908_pp0_iter2_reg <= and_ln29_reg_908_pp0_iter1_reg;
                icmp_ln24_3_reg_972_pp0_iter2_reg <= icmp_ln24_3_reg_972;
                icmp_ln24_3_reg_972_pp0_iter3_reg <= icmp_ln24_3_reg_972_pp0_iter2_reg;
                icmp_ln24_3_reg_972_pp0_iter4_reg <= icmp_ln24_3_reg_972_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln24_3_reg_972_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                and_ln34_reg_1028 <= and_ln34_fu_779_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                buffer_reg_1021 <= grp_fu_750_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln20_reg_853 <= icmp_ln20_fu_393_p2;
                icmp_ln20_reg_853_pp0_iter1_reg <= icmp_ln20_reg_853;
                icmp_ln20_reg_853_pp0_iter2_reg <= icmp_ln20_reg_853_pp0_iter1_reg;
                icmp_ln20_reg_853_pp0_iter3_reg <= icmp_ln20_reg_853_pp0_iter2_reg;
                icmp_ln20_reg_853_pp0_iter4_reg <= icmp_ln20_reg_853_pp0_iter3_reg;
                icmp_ln21_reg_864_pp0_iter1_reg <= icmp_ln21_reg_864;
                icmp_ln21_reg_864_pp0_iter2_reg <= icmp_ln21_reg_864_pp0_iter1_reg;
                icmp_ln21_reg_864_pp0_iter3_reg <= icmp_ln21_reg_864_pp0_iter2_reg;
                sub_ln29_reg_847 <= sub_ln29_fu_387_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                icmp_ln24_3_reg_972 <= icmp_ln24_3_fu_682_p2;
                select_ln24_8_reg_967 <= select_ln24_8_fu_543_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                in_d_reg_961 <= in_d_fu_530_p2;
                select_ln24_7_reg_945 <= select_ln24_7_fu_509_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then
                input_load_reg_996 <= input_r_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                merge_i_reg_1001 <= grp_fu_549_p66;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                mul_ln29_2_reg_1011 <= mul_ln29_2_fu_801_p2;
                select_ln24_reg_1006 <= select_ln24_fu_725_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then
                out_w_reg_927 <= out_w_fu_486_p2;
                select_ln24_6_reg_933 <= select_ln24_6_fu_495_p3;
                select_ln29_7_reg_921 <= select_ln29_7_fu_481_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                select_ln20_reg_916 <= select_ln20_fu_475_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_reg_853 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then
                select_ln21_reg_940 <= select_ln21_fu_503_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                sext_ln29_reg_835 <= sext_ln29_fu_361_p1;
                    shl_ln_reg_842(5 downto 3) <= shl_ln_fu_364_p3(5 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln19_fu_340_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                trunc_ln29_reg_825 <= trunc_ln29_fu_357_p1;
            end if;
        end if;
    end process;
    shl_ln_reg_842(2 downto 0) <= "000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln19_fu_340_p2, icmp_ln20_reg_853, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln19_fu_340_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (icmp_ln20_reg_853 = ap_const_lv1_1))) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (icmp_ln20_reg_853 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((not(((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    SeparableConv2D_2_b_s_address0 <= zext_ln23_fu_352_p1(3 - 1 downto 0);

    SeparableConv2D_2_b_s_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            SeparableConv2D_2_b_s_ce0 <= ap_const_logic_1;
        else 
            SeparableConv2D_2_b_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln19_fu_334_p2 <= std_logic_vector(unsigned(phi_mul_reg_254) + unsigned(ap_const_lv9_31));
    add_ln20_fu_432_p2 <= std_logic_vector(unsigned(indvar_flatten20_reg_266) + unsigned(ap_const_lv9_1));
    add_ln21_fu_417_p2 <= std_logic_vector(unsigned(ap_phi_mux_indvar_flatten_phi_fu_294_p4) + unsigned(ap_const_lv7_1));
    add_ln29_6_fu_525_p2 <= std_logic_vector(unsigned(zext_ln29_16_fu_522_p1) + unsigned(shl_ln_reg_842));
    add_ln29_7_fu_517_p2 <= std_logic_vector(signed(select_ln29_7_reg_921) + signed(zext_ln24_4_fu_514_p1));
    add_ln29_fu_427_p2 <= std_logic_vector(unsigned(sub_ln29_reg_847) + unsigned(zext_ln24_3_fu_423_p1));
    add_ln34_1_fu_705_p2 <= std_logic_vector(unsigned(zext_ln34_3_fu_702_p1) + unsigned(sext_ln29_7_fu_693_p1));
    add_ln34_fu_687_p2 <= std_logic_vector(unsigned(phi_mul_reg_254) + unsigned(zext_ln24_fu_540_p1));
    and_ln29_fu_470_p2 <= (xor_ln29_fu_465_p2 and icmp_ln24_reg_876);
    and_ln34_fu_779_p2 <= (trunc_ln33_fu_762_p1 and select_ln33_fu_771_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(5);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(6);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(7);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage2_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage2_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage1_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage2_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage1_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage2_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage2_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state6_assign_proc : process(icmp_ln20_reg_853)
    begin
        if ((icmp_ln20_reg_853 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state6 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state6 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln19_fu_340_p2)
    begin
        if ((((icmp_ln19_fu_340_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_buffer_0_phi_fu_327_p4_assign_proc : process(buffer_0_reg_324, icmp_ln20_reg_853_pp0_iter4_reg, ap_CS_fsm_pp0_stage1, buffer_reg_1021, ap_enable_reg_pp0_iter4, ap_block_pp0_stage1)
    begin
        if (((icmp_ln20_reg_853_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_phi_mux_buffer_0_phi_fu_327_p4 <= buffer_reg_1021;
        else 
            ap_phi_mux_buffer_0_phi_fu_327_p4 <= buffer_0_reg_324;
        end if; 
    end process;


    ap_phi_mux_in_d_0_phi_fu_305_p4_assign_proc : process(in_d_0_reg_301, ap_CS_fsm_pp0_stage0, icmp_ln20_reg_853, ap_enable_reg_pp0_iter1, in_d_fu_530_p2, ap_block_pp0_stage0)
    begin
        if (((icmp_ln20_reg_853 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_in_d_0_phi_fu_305_p4 <= in_d_fu_530_p2;
        else 
            ap_phi_mux_in_d_0_phi_fu_305_p4 <= in_d_0_reg_301;
        end if; 
    end process;


    ap_phi_mux_indvar_flatten20_phi_fu_270_p4_assign_proc : process(indvar_flatten20_reg_266, ap_CS_fsm_pp0_stage0, icmp_ln20_reg_853, add_ln20_reg_891, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((icmp_ln20_reg_853 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_indvar_flatten20_phi_fu_270_p4 <= add_ln20_reg_891;
        else 
            ap_phi_mux_indvar_flatten20_phi_fu_270_p4 <= indvar_flatten20_reg_266;
        end if; 
    end process;


    ap_phi_mux_indvar_flatten_phi_fu_294_p4_assign_proc : process(indvar_flatten_reg_290, ap_CS_fsm_pp0_stage0, icmp_ln20_reg_853, select_ln21_reg_940, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((icmp_ln20_reg_853 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_indvar_flatten_phi_fu_294_p4 <= select_ln21_reg_940;
        else 
            ap_phi_mux_indvar_flatten_phi_fu_294_p4 <= indvar_flatten_reg_290;
        end if; 
    end process;


    ap_phi_mux_out_h_0_phi_fu_282_p4_assign_proc : process(out_h_0_reg_278, ap_CS_fsm_pp0_stage0, icmp_ln20_reg_853, select_ln20_reg_916, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((icmp_ln20_reg_853 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_out_h_0_phi_fu_282_p4 <= select_ln20_reg_916;
        else 
            ap_phi_mux_out_h_0_phi_fu_282_p4 <= out_h_0_reg_278;
        end if; 
    end process;


    ap_phi_mux_out_w_0_phi_fu_317_p4_assign_proc : process(out_w_0_reg_313, icmp_ln20_reg_853_pp0_iter1_reg, ap_CS_fsm_pp0_stage1, select_ln24_7_reg_945, ap_enable_reg_pp0_iter1, ap_block_pp0_stage1)
    begin
        if (((icmp_ln20_reg_853_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_phi_mux_out_w_0_phi_fu_317_p4 <= select_ln24_7_reg_945;
        else 
            ap_phi_mux_out_w_0_phi_fu_317_p4 <= out_w_0_reg_313;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln19_fu_340_p2)
    begin
        if (((icmp_ln19_fu_340_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

        grp_fu_750_p0 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_737_p4),22));

    grp_fu_793_p0 <= grp_fu_793_p00(4 - 1 downto 0);
    grp_fu_793_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln24_6_reg_933),10));
    grp_fu_793_p1 <= ap_const_lv10_31(7 - 1 downto 0);
    icmp_ln19_fu_340_p2 <= "1" when (out_d_0_reg_243 = ap_const_lv4_8) else "0";
    icmp_ln20_fu_393_p2 <= "1" when (ap_phi_mux_indvar_flatten20_phi_fu_270_p4 = ap_const_lv9_188) else "0";
    icmp_ln21_fu_405_p2 <= "1" when (ap_phi_mux_indvar_flatten_phi_fu_294_p4 = ap_const_lv7_38) else "0";
    icmp_ln24_3_fu_682_p2 <= "1" when (in_d_reg_961 = ap_const_lv4_8) else "0";
    icmp_ln24_fu_411_p2 <= "1" when (ap_phi_mux_in_d_0_phi_fu_305_p4 = ap_const_lv4_8) else "0";
    in_d_fu_530_p2 <= std_logic_vector(unsigned(select_ln24_6_reg_933) + unsigned(ap_const_lv4_1));
    input_r_address0 <= zext_ln29_7_fu_714_p1(14 - 1 downto 0);

    input_r_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_enable_reg_pp0_iter2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)))) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln24_fu_491_p2 <= (icmp_ln21_reg_864 or and_ln29_reg_908);
    out_d_fu_346_p2 <= std_logic_vector(unsigned(out_d_0_reg_243) + unsigned(ap_const_lv4_1));
    out_h_fu_399_p2 <= std_logic_vector(unsigned(ap_phi_mux_out_h_0_phi_fu_282_p4) + unsigned(ap_const_lv3_1));
    out_w_fu_486_p2 <= std_logic_vector(unsigned(select_ln29_reg_896) + unsigned(ap_const_lv3_1));
    output_r_address0 <= zext_ln34_fu_788_p1(14 - 1 downto 0);

    output_r_ce0_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
            output_r_ce0 <= ap_const_logic_1;
        else 
            output_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_r_d0 <= and_ln34_reg_1028;

    output_r_we0_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, icmp_ln24_3_reg_972_pp0_iter4_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((icmp_ln24_3_reg_972_pp0_iter4_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
            output_r_we0 <= ap_const_logic_1;
        else 
            output_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln20_fu_475_p3 <= 
        out_h_reg_857 when (icmp_ln21_reg_864(0) = '1') else 
        out_h_0_reg_278;
    select_ln21_fu_503_p3 <= 
        ap_const_lv7_1 when (icmp_ln21_reg_864(0) = '1') else 
        add_ln21_reg_881;
    select_ln24_6_fu_495_p3 <= 
        ap_const_lv4_0 when (or_ln24_fu_491_p2(0) = '1') else 
        in_d_0_reg_301;
    select_ln24_7_fu_509_p3 <= 
        out_w_reg_927 when (and_ln29_reg_908(0) = '1') else 
        select_ln29_reg_896;
    select_ln24_8_fu_543_p3 <= 
        add_ln29_7_reg_951 when (and_ln29_reg_908(0) = '1') else 
        select_ln29_8_fu_535_p3;
    select_ln24_fu_725_p3 <= 
        sext_ln29_reg_835 when (and_ln29_reg_908_pp0_iter2_reg(0) = '1') else 
        select_ln29_6_fu_719_p3;
    select_ln29_6_fu_719_p3 <= 
        sext_ln29_reg_835 when (icmp_ln21_reg_864_pp0_iter3_reg(0) = '1') else 
        ap_phi_mux_buffer_0_phi_fu_327_p4;
    select_ln29_7_fu_481_p3 <= 
        sub_ln29_3_reg_902 when (icmp_ln21_reg_864(0) = '1') else 
        sub_ln29_reg_847;
    select_ln29_8_fu_535_p3 <= 
        sub_ln29_3_reg_902 when (icmp_ln21_reg_864_pp0_iter1_reg(0) = '1') else 
        add_ln29_reg_886;
    select_ln29_fu_438_p3 <= 
        ap_const_lv3_0 when (icmp_ln21_reg_864(0) = '1') else 
        ap_phi_mux_out_w_0_phi_fu_317_p4;
    select_ln33_fu_771_p3 <= 
        ap_const_lv16_FFFF when (xor_ln33_fu_765_p2(0) = '1') else 
        ap_const_lv16_0;
        sext_ln29_7_fu_693_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln29_7_reg_921),10));

        sext_ln29_8_fu_711_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln29_1_reg_981),32));

        sext_ln29_fu_361_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(SeparableConv2D_2_b_3_reg_830),22));

        sext_ln34_fu_785_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln34_1_reg_986_pp0_iter3_reg),32));

    shl_ln29_4_fu_375_p3 <= (ap_phi_mux_out_h_0_phi_fu_282_p4 & ap_const_lv3_0);
    shl_ln29_4_mid1_fu_448_p3 <= (out_h_reg_857 & ap_const_lv3_0);
    shl_ln_fu_364_p3 <= (trunc_ln29_reg_825 & ap_const_lv3_0);
    sub_ln29_3_fu_459_p2 <= std_logic_vector(unsigned(zext_ln29_14_fu_455_p1) - unsigned(zext_ln29_13_fu_445_p1));
    sub_ln29_fu_387_p2 <= std_logic_vector(unsigned(zext_ln29_12_fu_383_p1) - unsigned(zext_ln29_fu_371_p1));
    tmp_3_fu_755_p3 <= buffer_reg_1021(15 downto 15);
    trunc_ln29_fu_357_p1 <= out_d_0_reg_243(3 - 1 downto 0);
    trunc_ln33_fu_762_p1 <= buffer_reg_1021(16 - 1 downto 0);
    trunc_ln_fu_737_p4 <= mul_ln29_2_reg_1011(31 downto 14);
    xor_ln29_fu_465_p2 <= (icmp_ln21_reg_864 xor ap_const_lv1_1);
    xor_ln33_fu_765_p2 <= (tmp_3_fu_755_p3 xor ap_const_lv1_1);
    zext_ln23_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_d_0_reg_243),64));
    zext_ln24_3_fu_423_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_out_w_0_phi_fu_317_p4),7));
    zext_ln24_4_fu_514_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_w_reg_927),7));
    zext_ln24_fu_540_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln24_7_reg_945),9));
    zext_ln29_12_fu_383_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln29_4_fu_375_p3),7));
    zext_ln29_13_fu_445_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_h_reg_857),7));
    zext_ln29_14_fu_455_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln29_4_mid1_fu_448_p3),7));
    zext_ln29_16_fu_522_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln24_6_reg_933),6));
    zext_ln29_7_fu_714_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln29_8_fu_711_p1),64));
    zext_ln29_fu_371_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_out_h_0_phi_fu_282_p4),7));
    zext_ln34_3_fu_702_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln34_reg_976),10));
    zext_ln34_fu_788_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln34_fu_785_p1),64));
end behav;
